# Generated by Django 2.2.4 on 2019-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='description',
            field=models.TextField(default='', verbose_name='説明'),
        ),
    ]
